routes/web.php
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'FrontController@index');
Route::get('/home', 'FrontController@index');

Route::get('/panel', 'DashboardController@index');
Route::get('/admin', 'DashboardController@index');
Route::post('/admin/notificaciones', 'DashboardController@notificaciones');

Route::post('/admin/desmarcarnotificaciones', 'DashboardController@desmarcarnotificaciones');

Route::get('/admin/users', 'UsersController@listUsers');
Route::get('/admin/enterprises', 'EnterpriseController@listEnterprises');
Route::get('/admin/offers', 'JobOfferController@listOffers');
Route::get('/admin/news', 'NoticiaController@listNews');
Route::get('/admin/newsletters', 'NewsletterController@listNewsletters');
Route::get('/admin/studies/{id}/specialties', 'StudyController@specialties');
Route::get('/admin/province/{id}/concellos', 'ProvinceController@concellos');
Route::get('/admin/auditorys', 'AuditoriasController@listAuditorias');
Route::get('/admin/banners', 'BannerController@listBanners');
/* Route::get('/', function () {
  return redirect()->route('panel/index');
  }); */
Route::group(['prefix' => 'panel', /* 'middleware' => 'auth' */], function() {

    Route::post('/admin/ofertas/busquedaAvanzada', 'JobOfferController@index');
    Route::get('/admin/ofertas/{oferta_id}/inscripcion', 'JobOfferController@inscripcion');

    //Ruta para comprimir dv
    Route::get('/admin/ofertas/comprimir/{oferta_id}', 'JobOfferController@comprimirYDescargarZip')->name('comprimir');

    // ROUTE PARA DESCARGAR DOCUMENTOS USUARIOS
    Route::get('/admin/documentos/{user_id}/descargar', 'UsersController@descargarDocumentosUsuario');

    Route::post('/admin/ofertas/{oferta_id}/inscribirme', 'JobOfferController@inscribirme');
    Route::post('/admin/ofertas/inscribir', 'JobOfferController@confirmarInscripcion');
    //Route::post('/admin/ofertas/oferta_id', 'JobOfferController@confirmarInscripcion');
    Route::get('/admin/ofertas/{idOferta}/retirar/{idUser}', 'JobOfferController@retirarInscripcion');

    Route::get('/admin/ofertas/inscritos', 'JobOfferController@inscritos');

    Route::post('/admin/cursos/busquedaAvanzada', 'CursoController@index');
    Route::get('/admin/cursos/{curso_id}/inscripcion', 'CursoController@inscripcion');
    Route::post('/admin/cursos/{curso_id}/inscribirme', 'CursoController@inscribirme');
    Route::post('/admin/cursos/inscribir', 'CursoController@confirmarInscripcion');
    Route::get('/admin/cursos/{idCurso}/retirar/{idUser}', 'CursoController@retirarInscripcion');
    Route::resource('admin', 'DashboardController');


    Route::resource('boletin-ofertas', 'NewsletterController');
    Route::resource('auditorias', 'AuditoriasController');
    Route::get('/admin/empresas/{id}/remove', 'EnterpriseController@remove');
    Route::get('/admin/boletin-ofertas/{id}/remove', 'NewsletterController@remove');
    Route::get('/admin/ofertas/{id}/remove', 'JobOfferController@remove');
    Route::get('/admin/contratos/{id}/remove', 'ContractController@remove');
    Route::get('/admin/noticias/{id}/remove', 'NoticiaController@remove');
    Route::get('/admin/estudios/{id}/remove', 'EstudioController@remove');
    Route::get('/admin/especialidades/{id}/remove', 'SpecialtyController@remove');
    Route::get('/admin/permisos-conducir/{id}/remove', 'DrivingPermitController@remove');
    Route::get('/admin/usuarios/{id}/remove', 'UsersController@remove');
    Route::get('/admin/puestos/{id}/remove', 'PuestoController@remove');
    Route::get('/admin/sectores/{id}/remove', 'SectorController@remove');
    Route::get('/admin/boletines/{id}/remove', 'BoletinController@remove');
    Route::get('/admin/cursos/{id}/remove', 'CursoController@remove');
    Route::get('/admin/categorias/{id}/remove', 'CategoriaController@remove');
    Route::get('/admin/tipocursos/{id}/remove', 'TipoCursoController@remove');
    Route::get('/admin/disponibilidades/{id}/remove', 'DisponibilidadController@remove');
    Route::resource('sectores', 'SectorController');
    Route::get('/admin/banners/{id}/remove', 'BannerController@remove');



    //Route::get('/admin/boletines/{id}/edit2', 'BoletinController@edit2');

    Route::resource('boletines', 'BoletinController');

    Route::get('boletines2', 'BoletinController@index2');

    Route::get('/admin/boletines/{id}/generar', 'BoletinController@generar_boletin');
    Route::post('/admin/boletines/{id}/remove2', 'BoletinController@remove2');

    Route::get('/admin/boletines/{id}/edit2', 'BoletinController@edit2');

    Route::get('/admin/boletines/create2', 'BoletinController@create2');

    Route::post('/admin/boletines/store2', 'BoletinController@store2');
    Route::post('/admin/boletines/update2', 'BoletinController@update2');

    Route::resource('generos', 'GeneroController');
    Route::resource('categorias', 'CategoriaController');
    Route::resource('disponibilidades', 'DisponibilidadController');
    Route::resource('tipocursos', 'TipoCursoController');
    Route::resource('puestos', 'PuestoController');
    Route::resource('cursos', 'CursoController');
    Route::resource('contratos', 'ContractController');
    Route::resource('noticias', 'NoticiaController');
    Route::resource('estudios', 'EstudioController');
    Route::resource('especialidades', 'SpecialtyController');
    Route::resource('permisos-conducir', 'DrivingPermitController');
    Route::resource('ofertas', 'JobOfferController');
    Route::resource('usuarios', 'UsersController');
    Route::resource('banners', 'BannerController');



    Route::post('/admin/chart1', 'DashboardController@chart1');






    //Route::get('/admin', 'HomeController@index')->name('admin');

    Route::get('/admin/noticias/{id}/remove/{img}', 'NoticiaController@removeimgd')->name('noticias.removeimgd');
    Route::get('/admin/noticias/{id}/remove1/{img}', 'NoticiaController@removeimg1')->name('noticias.removeimg1');
    Route::get('/admin/noticias/{id}/remove2/{img}', 'NoticiaController@removeimg2')->name('noticias.removeimg2');

    Route::get('/admin/banners/{id}/remove/{img}', 'BannerController@removeimgd')->name('banners.removeimgd');

    Route::get('/admin/ofertas/{id}/remove/{img}', 'JobOfferController@removeimgd')->name('ofertas.removeimgd');

    Route::post('/admin/chart1', 'DashboardController@chart1');

    Route::get('/admin/boletines/{id}/ofertasinternas', 'BoletinController@ofertasinternas');
    Route::post('/admin/boletines/ofertainterna/remove', 'BoletinController@ofertasinternas_remove');
    Route::post('/admin/boletines/listarofertasinternas', 'BoletinController@ofertasinternas_listar');
    Route::post('/admin/boletines/guardarofertasinternas', 'BoletinController@ofertasinternas_guardar');
    Route::post('/admin/boletines/updateofertasinternas', 'BoletinController@ofertasinternas_update');


    Route::get('/admin/boletines/{id}/ofertasexternas', 'BoletinController@ofertasexternas');
    Route::post('/admin/boletines/ofertaexterna/remove', 'BoletinController@ofertasexternas_remove');
    Route::post('/admin/boletines/listarofertasexternas', 'BoletinController@ofertasexternas_listar');
    Route::post('/admin/boletines/guardarofertasexternas', 'BoletinController@ofertasexternas_guardar');
    Route::post('/admin/boletines/updateofertasexternas', 'BoletinController@ofertasexternas_update');


  
    
    Route::post('/admin/ofertas/actualizar_campo', 'JobOfferController@actualizarCampo');

    Route::post('/admin/ofertas/actualizar_campo', 'JobOfferController@actualizarCampo');

    Route::post('/admin/ofertas/actualizar_rematado', 'JobOfferController@actualizarRematado');

    Route::get('/sepe-estadisticas', 'JobOfferController@sepeEstadisticas');

    Route::get('/descargarXml', 'JobOfferController@descargarXml');


Route::resource('sectores_ofertas', 'SectorOfertaController');

    Route::get('/admin/sectores_ofertas', 'SectorOfertaController@index');

    Route::get('/admin/sectores_ofertas/create', 'SectorOfertaController@create');

    Route::post('/admin/sectores_ofertas/store', 'SectorOfertaController@store');

    Route::get('/admin/sectores_ofertas/{id}/edit', 'SectorOfertaController@edit');

    Route::post('/admin/sectores_ofertas/update', 'SectorOfertaController@update');

    Route::get('/admin/sectores_ofertas/{id}/remove', 'SectorOfertaController@remove');
});





Route::get('/estudios/{id}/especialidades', 'EstudioController@especialidades');
Route::get('/province/{id}/concellos', 'ProvinceController@concellos');
Route::get('/bajarcv/{filename}/', 'UsersController@downloadcv');
Route::get("/getFoto/{nombre}", 'UsersController@descargarFoto');

Route::post('user/login', 'UsersController@login');

Route::post('user/darsedebaja', 'UsersController@darsedebaja');

Route::post('user/obtenercertificado', 'UsersController@obtenerCertificado');

Route::post('user/dardebaja', 'UsersController@dardebaja');


Route::get('user/logout', 'UsersController@logout');

Route::post('user/resetpassword', 'UsersController@resetpassword');

Route::post('cursos/buscardatos', 'CursoController@buscardatos');
Route::post('ofertas/buscardatos', 'JobOfferController@buscardatos');

Route::get('registrarperfil', 'FrontController@registrarPerfil');
Route::get('editarperfil', 'FrontController@editarPerfil');

Route::get('/ofertas', 'FrontController@ofertas');
//Route::get('oferta-ficha/{id}', 'FrontController@ofertaFicha');
Route::get('ofertas/{id}/{slug}', 'FrontController@ofertaFicha');

Route::get('ofertas/buscar', 'FrontController@buscarOfertas');

Route::get('ofertasempresa/{slug}', 'FrontController@ofertasEmpresa');

Route::get('formacion', 'FrontController@cursos');
Route::get('curso-ficha/{id}', 'FrontController@cursoFicha');
Route::get('formacion/{id}/{slug}', 'FrontController@cursoFicha');

Route::get('actualidade', 'FrontController@actualidade');

app/Http/Controllers/SpecialtyController.php
<?php

namespace App\Http\Controllers;
use Validator;
use App\Entities\Specialty;
use App\Entities\Grade;

use Illuminate\Http\Request;

class SpecialtyController extends Controller
{
     public function __construct() {
        $this->middleware('auth');
        $this->middleware('admin', ['only' => ['index','create','edit','remove']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $specialties = Specialty::all();
        $message = 'No hay especialidades registradas';
        return view('specialty.index')->with(['specialties' => $specialties, 'message' => $message]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $grades = Grade::all();
        return view('specialty.create')->with(['grades'=>$grades]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $specialty = new Specialty();
        $specialty->description = $request->input('description');
         $specialty->nome = $request->input('nome');
        $specialty->grade_id = $request->input('grade_id');
        $editados = json_encode($specialty->getDirty());
        $specialty->save();
         \App\Entities\Auditoria::create([
                'model_name' => 'Especialidades',
                'user_id' => \Illuminate\Support\Facades\Auth::user()->pk,
                'action' => 'Creó el registro '. $specialty->id . ' '. $editados,
                'original_set' => $specialty->toJson(),
                'changed_set' => ''
            ]);
         
        $request->session()->flash('alert-success', 'Especialidad creado correctamente');
        return redirect()->route('especialidades.index')->withInput();
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $specialty = Specialty::findOrFail($id);
        $grades = Grade::all();
        return view('specialty.edit')->with(['specialty' => $specialty,'grades'=>$grades]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $values = array('description','nome','grade_id');
        $especialidad= Specialty::find($id);
        $original = $especialidad->toJson();
        $editados = json_encode($request->all($values));
        
        $especialidad->update($request->all($values));
        
        if($original != json_encode($request->all($values))){
        \App\Entities\Auditoria::create([
                'model_name' => 'Especialidades',
                'user_id' => \Illuminate\Support\Facades\Auth::user()->pk,
                'action' => 'Actualizó el registro '. $especialidad->id . ' '. $editados,
                'original_set' => $original,
                'changed_set' => json_encode($request->all($values))
            ]);
        }
        
        $request->session()->flash('alert-success', 'Especialidades editado correctamente');
        return redirect()->route('especialidades.index')->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        Specialty::destroy($id);
        $request->session()->flash('alert-success', 'Especialidades eliminado correctamente');
        return redirect()->route('especialidades.index')->withInput();
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function show(Contract  $puesto)
    {}
    public function remove(Request $request, $id)
    {
        $specialty= Specialty::find($id);
        $original = $specialty->toJson();
        $specialty->delete();
        
         \App\Entities\Auditoria::create([
                'model_name' => 'Especialidades',
                'user_id' => \Illuminate\Support\Facades\Auth::user()->pk,
                'action' => 'Eliminar el registro',
                'original_set' => $original,
                'changed_set' => ''
            ]);
         
         
        $request->session()->flash('alert-success', 'Especialidad eliminada correctamente');
        return redirect()->route('especialidades.index');
    }
}

resources/views/specialty/create.blade.php
@extends('layouts.app')

@section('titulo_pantalla')

@endsection

@section('content')
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i>{{__('specialty.errors')}}</h4>
    @foreach ($errors->all() as $error)
    <p>{{ $error }}</p>
    @endforeach
</div>
@endif

@if(Session::has('alert-success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> {{ Session::get('alert-success') }}</h4>
</div>
@endif
<form style="padding: 30px;" id="specialtyForm" method="POST" novalidate action="{{url('/panel/especialidades')}}" accept-charset="UTF-8" class="form-horizontal">
    {{ csrf_field() }}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div>
                        {{__('specialty.new_specialty_label')}}
                    </div>
                </div>
                <div class="card-body">
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('Grado / Estudio')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">
                                <select class="form-control" name="grade_id">
                                    @foreach($grades as $grade)
                                    <option value="{{$grade->id}}">{{ session('lang')=='es' ?  $grade->description :  $grade->nome }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('Nombre')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="description" required>
                            </div>
                        </div>
                    </fieldset>
                     <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('Nome')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="nome" required value="">
                            </div>
                        </div>
                    </fieldset>
                    
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary custom-btn" name="signup" value="Sign up">{{__('specialty.save')}}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
@endsection

resources/views/specialty/edit.blade.php
@extends('layouts.app')

@section('titulo_pantalla')

@endsection

@section('content')
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i>{{__('specialty.errors')}}</h4>
    @foreach ($errors->all() as $error)
    <p>{{ $error }}</p>
    @endforeach
</div>
@endif

@if(Session::has('alert-success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> {{ Session::get('alert-success') }}</h4>
</div>
@endif
<form style="padding: 30px;" id="specialtyForm" method="POST" action="{{route('especialidades.update', $specialty->id) }}" accept-charset="UTF-8" class="form-group">
    {{method_field('PATCH')}}
    {{ csrf_field() }}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div>
                        {{__('Editar Especialidades')}}
                    </div>
                </div>
                <div class="card-body">
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('specialty.grade')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">
                                <select class="form-control" name="grade_id">
                                    @foreach($grades as $grade)
                                    <option {{$grade->id===$specialty->grade_id? 'selected':''}} value="{{$grade->id}}">{{$grade->description}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('Nombre')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="description" required value="{{ strtoupper($specialty->description) }}">
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('Nome')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="nome" required value="{{ strtoupper($specialty->nome) }}">
                            </div>
                        </div>
                    </fieldset>
                    
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary custom-btn" name="signup" value="Sign up">{{__('specialty.save')}}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
@endsection

resources/views/specialty/index.blade.php
@extends('layouts.app')

@section('title_pestaña')
| Elegir Evento
@endsection

@section('titulo_pantalla')

@endsection
@section('breadcrumb')
<ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item active">Especialidades</li>
    <!-- Breadcrumb Menu-->
</ol>
@endsection
@section('content')
@if(Session::has('alert-success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> {{ Session::get('alert-success') }}</h4>
</div>
@endif
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">{{__('Especialidades')}}
               
            </div>
            <div class="card-body">
                <div class="toolbar">
                    <div class="btn-group">
                        <a class="btn btn-block btn-outline-primary" href="{{ url('/panel/especialidades/create') }}"><i class="fa fa-plus-circle" aria-hidden="true"> </i> {{__('specialty.add')}}</a>
                    </div>
                </div>
                <table id="specialty-table" class="table table-striped table-bordered table-hover dataTable no-footer">
                    <thead class="thead-light">
                        <tr>
                            <th style="width: 25%">{{__('Grado / Estudio')}}</th>
                            <th style="width: 30%">Nombre</th>
                            <th style="width: 30%">Nome</th>
                            
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($specialties as $specialty)
                        <tr>
                             <td>{{ $specialty->Study->description }}</td>
                            <td>{{ $specialty->description }}</td>
                            <td>{{ $specialty->nome }}</td>
                           
                            <td style="text-align:center; vertical-align:middle;">
                                <a href='{{url('/panel/especialidades/'.$specialty->id.'/edit')}}' title='Edit' ><span class='glyphicon glyphicon-edit'></span></a>
                                &emsp;<a id='remove_link' href='{{url('/panel/admin/especialidades/'.$specialty->id.'/remove')}}' title='Delete' ><span class='glyphicon glyphicon-remove' style='color:red'></span></a>
                            </td>
                        </tr>
                        @endforeach	
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>
<!-- /.row-->
@endsection