routes/web.php
<?php

use Spatie\Sitemap\SitemapGenerator;
use Spatie\Sitemap\Tags\Url;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', 'FrontController@index');
Route::get('/home', 'FrontController@index');

Route::get('/panel', 'DashboardController@index');
Route::get('/admin', 'DashboardController@index');
Route::post('/admin/notificaciones', 'DashboardController@notificaciones');

Route::post('/admin/desmarcarnotificaciones', 'DashboardController@desmarcarnotificaciones');

Route::get('/admin/users', 'UsersController@listUsers');
Route::get('/admin/enterprises', 'EnterpriseController@listEnterprises');
Route::get('/admin/offers', 'JobOfferController@listOffers');
Route::get('/admin/news', 'NoticiaController@listNews');
Route::get('/admin/newsletters', 'NewsletterController@listNewsletters');
Route::get('/admin/studies/{id}/specialties', 'StudyController@specialties');
Route::get('/admin/province/{id}/concellos', 'ProvinceController@concellos');
Route::get('/admin/auditorys', 'AuditoriasController@listAuditorias');
Route::get('/admin/banners', 'BannerController@listBanners');
/* Route::get('/', function () {
  return redirect()->route('panel/index');
  }); */
Route::group(['prefix' => 'panel', /* 'middleware' => 'auth' */], function() {

    Route::post('/admin/ofertas/busquedaAvanzada', 'JobOfferController@index');
    Route::get('/admin/ofertas/{oferta_id}/inscripcion', 'JobOfferController@inscripcion');

    //Ruta para comprimir dv
    Route::get('/admin/ofertas/comprimir/{oferta_id}', 'JobOfferController@comprimirYDescargarZip')->name('comprimir');

    // ROUTE PARA DESCARGAR DOCUMENTOS USUARIOS
    Route::get('/admin/documentos/{user_id}/descargar', 'UsersController@descargarDocumentosUsuario');

    Route::post('/admin/ofertas/{oferta_id}/inscribirme', 'JobOfferController@inscribirme');
    Route::post('/admin/ofertas/inscribir', 'JobOfferController@confirmarInscripcion');
    //Route::post('/admin/ofertas/oferta_id', 'JobOfferController@confirmarInscripcion');
    Route::get('/admin/ofertas/{idOferta}/retirar/{idUser}', 'JobOfferController@retirarInscripcion');

    Route::get('/admin/ofertas/inscritos', 'JobOfferController@inscritos');

    Route::post('/admin/cursos/busquedaAvanzada', 'CursoController@index');
    Route::get('/admin/cursos/{curso_id}/inscripcion', 'CursoController@inscripcion');
    Route::post('/admin/cursos/{curso_id}/inscribirme', 'CursoController@inscribirme');
    Route::post('/admin/cursos/inscribir', 'CursoController@confirmarInscripcion');
    Route::get('/admin/cursos/{idCurso}/retirar/{idUser}', 'CursoController@retirarInscripcion');
    Route::resource('admin', 'DashboardController');


    Route::resource('boletin-ofertas', 'NewsletterController');
    Route::resource('auditorias', 'AuditoriasController');
    Route::get('/admin/empresas/{id}/remove', 'EnterpriseController@remove');
    Route::get('/admin/boletin-ofertas/{id}/remove', 'NewsletterController@remove');
    Route::get('/admin/ofertas/{id}/remove', 'JobOfferController@remove');
    Route::get('/admin/contratos/{id}/remove', 'ContractController@remove');
    Route::get('/admin/noticias/{id}/remove', 'NoticiaController@remove');
    Route::get('/admin/estudios/{id}/remove', 'EstudioController@remove');
    Route::get('/admin/especialidades/{id}/remove', 'SpecialtyController@remove');
    Route::get('/admin/permisos-conducir/{id}/remove', 'DrivingPermitController@remove');
    Route::get('/admin/usuarios/{id}/remove', 'UsersController@remove');
    Route::get('/admin/puestos/{id}/remove', 'PuestoController@remove');
    Route::get('/admin/sectores/{id}/remove', 'SectorController@remove');
    Route::get('/admin/boletines/{id}/remove', 'BoletinController@remove');
    Route::get('/admin/cursos/{id}/remove', 'CursoController@remove');
    Route::get('/admin/categorias/{id}/remove', 'CategoriaController@remove');
    Route::get('/admin/tipocursos/{id}/remove', 'TipoCursoController@remove');
    Route::get('/admin/disponibilidades/{id}/remove', 'DisponibilidadController@remove');
    Route::resource('sectores', 'SectorController');
    Route::get('/admin/banners/{id}/remove', 'BannerController@remove');



    //Route::get('/admin/boletines/{id}/edit2', 'BoletinController@edit2');

    Route::resource('boletines', 'BoletinController');

    Route::get('boletines2', 'BoletinController@index2');

    Route::get('/admin/boletines/{id}/generar', 'BoletinController@generar_boletin');
    Route::post('/admin/boletines/{id}/remove2', 'BoletinController@remove2');

    Route::get('/admin/boletines/{id}/edit2', 'BoletinController@edit2');

    Route::get('/admin/boletines/create2', 'BoletinController@create2');

    Route::post('/admin/boletines/store2', 'BoletinController@store2');
    Route::post('/admin/boletines/update2', 'BoletinController@update2');

    Route::resource('generos', 'GeneroController');
    Route::resource('categorias', 'CategoriaController');
    Route::resource('disponibilidades', 'DisponibilidadController');
    Route::resource('tipocursos', 'TipoCursoController');
    Route::resource('puestos', 'PuestoController');
    Route::resource('cursos', 'CursoController');
    Route::resource('contratos', 'ContractController');
    Route::resource('noticias', 'NoticiaController');
    Route::resource('estudios', 'EstudioController');
    Route::resource('especialidades', 'SpecialtyController');
    Route::resource('permisos-conducir', 'DrivingPermitController');
    Route::resource('ofertas', 'JobOfferController');
    Route::resource('usuarios', 'UsersController');
    Route::resource('banners', 'BannerController');



    Route::post('/admin/chart1', 'DashboardController@chart1');






    //Route::get('/admin', 'HomeController@index')->name('admin');

    Route::get('/admin/noticias/{id}/remove/{img}', 'NoticiaController@removeimgd')->name('noticias.removeimgd');
    Route::get('/admin/noticias/{id}/remove1/{img}', 'NoticiaController@removeimg1')->name('noticias.removeimg1');
    Route::get('/admin/noticias/{id}/remove2/{img}', 'NoticiaController@removeimg2')->name('noticias.removeimg2');

    Route::get('/admin/banners/{id}/remove/{img}', 'BannerController@removeimgd')->name('banners.removeimgd');

    Route::get('/admin/ofertas/{id}/remove/{img}', 'JobOfferController@removeimgd')->name('ofertas.removeimgd');

    Route::post('/admin/chart1', 'DashboardController@chart1');

    Route::get('/admin/boletines/{id}/ofertasinternas', 'BoletinController@ofertasinternas');
    Route::post('/admin/boletines/ofertainterna/remove', 'BoletinController@ofertasinternas_remove');
    Route::post('/admin/boletines/listarofertasinternas', 'BoletinController@ofertasinternas_listar');
    Route::post('/admin/boletines/guardarofertasinternas', 'BoletinController@ofertasinternas_guardar');
    Route::post('/admin/boletines/updateofertasinternas', 'BoletinController@ofertasinternas_update');


    Route::get('/admin/boletines/{id}/ofertasexternas', 'BoletinController@ofertasexternas');
    Route::post('/admin/boletines/ofertaexterna/remove', 'BoletinController@ofertasexternas_remove');
    Route::post('/admin/boletines/listarofertasexternas', 'BoletinController@ofertasexternas_listar');
    Route::post('/admin/boletines/guardarofertasexternas', 'BoletinController@ofertasexternas_guardar');
    Route::post('/admin/boletines/updateofertasexternas', 'BoletinController@ofertasexternas_update');


  
    
    Route::post('/admin/ofertas/actualizar_campo', 'JobOfferController@actualizarCampo');

    Route::post('/admin/ofertas/actualizar_campo', 'JobOfferController@actualizarCampo');

    Route::post('/admin/ofertas/actualizar_rematado', 'JobOfferController@actualizarRematado');

    Route::get('/sepe-estadisticas', 'JobOfferController@sepeEstadisticas');

    Route::get('/descargarXml', 'JobOfferController@descargarXml');


Route::resource('sectores_ofertas', 'SectorOfertaController');

    Route::get('/admin/sectores_ofertas', 'SectorOfertaController@index');

    Route::get('/admin/sectores_ofertas/create', 'SectorOfertaController@create');

    Route::post('/admin/sectores_ofertas/store', 'SectorOfertaController@store');

    Route::get('/admin/sectores_ofertas/{id}/edit', 'SectorOfertaController@edit');

    Route::post('/admin/sectores_ofertas/update', 'SectorOfertaController@update');

    Route::get('/admin/sectores_ofertas/{id}/remove', 'SectorOfertaController@remove');
});





Route::get('/estudios/{id}/especialidades', 'EstudioController@especialidades');
Route::get('/province/{id}/concellos', 'ProvinceController@concellos');
Route::get('/bajarcv/{filename}/', 'UsersController@downloadcv');
Route::get("/getFoto/{nombre}", 'UsersController@descargarFoto');

Route::post('user/login', 'UsersController@login');

Route::post('user/darsedebaja', 'UsersController@darsedebaja');

Route::post('user/obtenercertificado', 'UsersController@obtenerCertificado');

Route::post('user/dardebaja', 'UsersController@dardebaja');


Route::get('user/logout', 'UsersController@logout');

Route::post('user/resetpassword', 'UsersController@resetpassword');

Route::post('cursos/buscardatos', 'CursoController@buscardatos');
Route::post('ofertas/buscardatos', 'JobOfferController@buscardatos');

Route::get('registrarperfil', 'FrontController@registrarPerfil');
Route::get('editarperfil', 'FrontController@editarPerfil');

Route::get('/ofertas', 'FrontController@ofertas');
//Route::get('oferta-ficha/{id}', 'FrontController@ofertaFicha');
Route::get('ofertas/{id}/{slug}', 'FrontController@ofertaFicha');

Route::get('ofertas/buscar', 'FrontController@buscarOfertas');

resources/views/boletin/create.blade.php
@extends('layouts.app')

@section('titulo_pantalla')

@endsection

@section('content')
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i>{{__('boletin.errors')}}</h4>
    @foreach ($errors->all() as $error)
    <p>{{ $error }}</p>
    @endforeach
</div>
@endif
@if(Session::has('alert-danger'))
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-danger"></i> {{ Session::get('alert-danger') }}</h4>
</div>
@endif
@if(Session::has('alert-success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> {{ Session::get('alert-success') }}</h4>
</div>
@endif
<form style="padding: 30px;" id="boletinForm" method="POST" action="{{url('/panel/boletines')}}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
    {{ csrf_field() }}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div>
                        {{__('boletin.new_boletin_label')}}
                    </div>
                </div>
                <div class="card-body">
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('boletin.name')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="nombre" required>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('boletin.name_gl')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="nome" required>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('boletin.Boletin')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                               <input id="boletin" type="file" name="boletin" accept="application/pdf,image/jpeg" required>
                            </div>
                        </div>
                    </fieldset>
                    
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary custom-btn" name="signup" value="Sign up">{{__('boletin.save')}}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>	
</div>
@endsection

resources/views/boletin/edit.blade.php
@extends('layouts.app')

@section('titulo_pantalla')

@endsection

@section('content')
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i>{{__('boletin.errors')}}</h4>
    @foreach ($errors->all() as $error)
    <p>{{ $error }}</p>
    @endforeach
</div>
@endif

@if(Session::has('alert-success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> {{ Session::get('alert-success') }}</h4>
</div>
@endif
<form style="padding: 30px;" id="boletinForm" method="POST" action="{{route('boletines.update', $boletin->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
    {{method_field('PATCH')}}
    {{ csrf_field() }}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div>
                        {{__('boletin.edit_boletin_label')}}
                    </div>
                </div>
                <div class="card-body">
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('boletin.name')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="nombre" value="{{$boletin->nombre}}" required>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('boletin.name_gl')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input type="text" class="form-control" name="nome" required value="{{$boletin->nome}}">
                            </div>
                        </div>
                    </fieldset>
                    <fieldset id="" role="group" aria-labelledby="__BVID__232__BV_label_" aria-describedby="__BVID__232__BV_description_" class="b-form-group form-group">
                        <legend id="__BVID__232__BV_label_" class="col-form-label pt-0">{{__('boletin.Boletin')}}</legend>
                        <div role="group" aria-labelledby="__BVID__232__BV_label_" class="">
                            <div role="group" class="input-group">								
                                <input id="boletin" type="file" name="boletin" accept="application/pdf,image/jpeg" 
                                <?php
                                if ($boletin->link == '') {
                                    echo 'required';
                                }
                                ?>>
                                </br>
                               
                            </div>
                            <br>
                             <a href="{{'/public'.$boletin->link}} "target="_blank">{{ $boletin->link }} </a>
                        </div>
                    </fieldset>

                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary custom-btn" name="signup" value="Sign up">{{__('boletin.save')}}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@endsection

resources/views/boletin/index.blade.php
@extends('layouts.app')

@section('title_pestaña')
| Elegir Evento
@endsection

@section('titulo_pantalla')

@endsection
@section('breadcrumb')
<ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item active">{{__('boletin.boletines')}}</li>
    <!-- Breadcrumb Menu-->
</ol>
@endsection

@section('content')
@if(Session::has('alert-success'))
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> {{ Session::get('alert-success') }}</h4>
</div>
@endif
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">{{__('boletin.boletines')}}
                
            </div>
            <div class="card-body">
                <div class="toolbar">
                    <div class="btn-group">
                        <a class="btn btn-block btn-outline-primary" href="{{ url('/panel/boletines/create') }}"><i class="fa fa-plus-circle" aria-hidden="true"> </i> {{__('boletin.add')}}</a>
                    </div>
                </div>
                @if($boletines->count())

                <table id="boletines-table" class="table table-striped table-bordered table-hover dataTable no-footer">
                    <thead class="thead-light">
                        <tr>
                            <th>{{__('boletin.name')}}</th>
                            <th>{{__('boletin.name_gl')}}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($boletines as $boletin)
                        <tr>
                            <td>{{ $boletin->nombre }}</td>
                            <td>{{ $boletin->nome }}</td>
                            <td><a href="{{'/public'.($boletin->link)}}" target="_blank"> {{ $boletin->link }} </a></td>

                            <td style="text-align:center; vertical-align:middle;">
                                <a href='{{url('/panel/boletines/'.$boletin->id.'/edit')}}' title='Edit' ><span class='glyphicon glyphicon-edit'></span></a>
                                &emsp;<a id='remove_link' href='{{url('/panel/admin/boletines/'.$boletin->id.'/remove')}}' title='Delete' ><span class='glyphicon glyphicon-remove' style='color:red'></span></a>
                            </td>
                        </tr>
                        @endforeach	
                    </tbody>
                </table>
                @else
                <p style="text-align:center;">{{ $message }}</p>
                @endif
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>
<!-- /.row-->
@endsection